# This file contians unstable rustfmt options that developers should enable when changing this crate.
# As these options require the use of a nightly toolchain, however, they're not added to the default configuration file.
# To use these options, exclude `.rustfmt.toml` in your `.git/info/exclude` file and append this file to it.

unstable_features = true
format_strings = true
wrap_comments = true
comment_width = 120
error_on_unformatted = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
imports_granularity = "Module"
